version: '3.8'
services:
  nestjs:
    container_name: nestjs-flow
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      # - rabbitmq
    networks:
      - nestjs_network

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - '5432-5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env.docker
    networks:
      - nestjs_network

  pgadmin:
    links:
     - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env.docker
    networks:
      - nestjs_network
    logging:
      driver: none

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - nestjs_network
    logging:
      driver: none

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis
    networks:
      - nestjs_network
    logging:
      driver: none

  # Only when use Microservice with RabbitMQ
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   hostname: rabbitmq
  #   volumes:
  #     - /var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   env_file:
  #     - .env.rabbitmq
  #   logging:
  #     driver: none
  #   networks:
  #     -  nestjs_network

# Elasticsearch
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    logging:
      driver: none
    networks:
      - nestjs_network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    logging:
      driver: none
    networks:
      - nestjs_network
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    logging:
      driver: none
    networks:
      - nestjs_network

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  nestjs_network:
    driver: bridge
    name: nestjs_network
