version: "3.8"
services:
  nestjs:
    image: nestjs-flow
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  nginx:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nestjs
    environment:
      - NGINX_SERVER_NAME=_
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80


  postgres:
    image: postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env.docker
    ports:
      - '5432-5432'
    volumes:
      - /data/postgres:/data/postgres

  pgadmin:
    links:
     - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env.docker
    logging:
      driver: none

  # Elasticsearch
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

